
development:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sgtran_development
  pool: 5
  username: root
  password: root

test: &TEST
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sgtran_test
  pool: 5
  username: root
  password: root

production:
  adapter: mysql
  encoding: utf8
  reconnect: false
  database: sgtran_production
  pool: 5
  username: root
  password: root


cucumber:
  <<: *TEST

